theme = "vu"

[editor]
true-color = true
color-modes = true
idle-timeout = 75

[editor.file-picker]
hidden = false
git-ignore = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-s = ":write"

# Some nice Helix stuff
A-h = "select_prev_sibling"
A-k = "shrink_selection"
A-j = "expand_selection"
A-l = "select_next_sibling"

# Personal preference
# o = ["open_below", "normal_mode"]
# O = ["open_above", "normal_mode"]
# 
# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection"]

C-n = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{/bin/cat /tmp/unique-file}',
  ':redraw',
]
