theme = "vu"

[editor]
true-color = true
color-modes = true
idle-timeout = 75

[editor.file-picker]
hidden = false
git-ignore = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-s = ":write"
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

# Some nice Helix stuff
A-h = "select_prev_sibling"
A-k = "shrink_selection"
A-j = "expand_selection"
A-l = "select_next_sibling"

# Personal preference
# o = ["open_below", "normal_mode"]
# O = ["open_above", "normal_mode"]

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection"]
